AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvName:
    Type: String
  ReleaseHash:
    Type: String
  StackPrefix:
    Type: String
    Default: "plaax"

Resources:
  LambdaApi1:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: "Just a test lambda LambdaApi1"
      FunctionName: !Sub "${StackPrefix}-${EnvName}-lbapi1"
      Handler: "awsLambdas/api/index.handler" # = <path?><fileNameNoExt>.handler
      Code:
        S3Bucket: "plaax-releases"
        S3Key: !Sub "${EnvName}/release-lbapi1-${ReleaseHash}.zip"
      PackageType: "Zip"
      Role: !GetAtt "LambdaApi1Role.Arn"
      Runtime: "nodejs18.x"
      #MemorySize: 256
      #Timeout: 30
      Environment:
        Variables:
          NODE_OPTIONS: "--enable-source-maps"

  LambdaApi1LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      # Description: "Log group for LambdaApi1" # property not allowed for AWS::Logs::LogGroup
      LogGroupName: !Sub "/aws/lambda/${LambdaApi1}"
      RetentionInDays: 7

  LambdaApi1Role:
    Type: "AWS::IAM::Role"
    Properties:
      Description: "Role and policies for LambdaApi1 to write logs"
      RoleName: !Sub "${StackPrefix}-${EnvName}-lbapi1-role"
      Policies:
        - PolicyName: !Sub "${StackPrefix}-${EnvName}-lbapi1-cloudwatch-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action: sts:AssumeRole

  ApiGw1Rest:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Description: "Just an API Gateway Gw1 which triggers LambdaApi1"
      ProtocolType: HTTP
      Name: !Sub "${StackPrefix}-${EnvName}-gw1"

  ApiGw1IamRole:
    Type: AWS::IAM::Role
    Properties:
      Description: "Role and policies for Gateway1 to access lambda"
      RoleName: !Sub "${StackPrefix}-${EnvName}-gw1-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ""
            Effect: "Allow"
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "access-to-lbapi1"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "lambda:*"
                Resource: !GetAtt LambdaApi1.Arn

  ApiGw1IntegrationWithLambdaApi1:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      Description: "Definition of how LambdaApi1 and Gateway1 should interact"
      ApiId: !Ref ApiGw1Rest
      ConnectionType: INTERNET # or VPC_LINK for internal connections: todo?
      CredentialsArn: !GetAtt ApiGw1IamRole.Arn
      PassthroughBehavior: WHEN_NO_MATCH # send the request 'as it is' to AWS service
      TimeoutInMillis: 29000
      IntegrationMethod: POST # mandatory for lambda invocations
      IntegrationType: AWS_PROXY # send the request 'as it is' to AWS service
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaApi1.Arn}/invocations"

  ApiGw1Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      # Prevents the error: "Unable to deploy API because no routes exist in this API..."
      - ApiGw1RouteGetProject
      - ApiGw1RouteCreateItem
      - ApiGw1RouteGetUserCalendar
      - ApiGw1RouteGetUserProjects
    Properties:
      Description: "Deployment for API Gateway1"
      ApiId: !Ref ApiGw1Rest

  ApiGw1StageV1:
    Type: AWS::ApiGatewayV2::Stage
    DependsOn:
      - ApiGw1Rest
      - ApiGw1Deployment
    Properties:
      Description: "Stage v1 for API Gateway1"
      StageName: "v1"
      ApiId: !Ref ApiGw1Rest
      DeploymentId: !Ref ApiGw1Deployment

  ApiGw1RouteGetProject:
    Type: AWS::ApiGatewayV2::Route
    DependsOn:
      - ApiGw1Rest
      - ApiGw1IntegrationWithLambdaApi1
    Properties:
      # Description: "Route to LambdaApi1 for API Gateway1" # property not allowed for AWS::ApiGatewayV2::Route
      ApiId: !Ref ApiGw1Rest
      RouteKey: GET /project/{projectId}
      Target: !Join
        - /
        - - integrations
          - !Ref ApiGw1IntegrationWithLambdaApi1

  ApiGw1RouteCreateItem:
    Type: AWS::ApiGatewayV2::Route
    DependsOn:
      - ApiGw1Rest
      - ApiGw1IntegrationWithLambdaApi1
    Properties:
      # Description: "Route to LambdaApi1 for API Gateway1" # property not allowed for AWS::ApiGatewayV2::Route
      ApiId: !Ref ApiGw1Rest
      RouteKey: POST /item # body with userId and projectId mandatory
      Target: !Join
        - /
        - - integrations
          - !Ref ApiGw1IntegrationWithLambdaApi1

  ApiGw1RouteGetUserCalendar:
    Type: AWS::ApiGatewayV2::Route
    DependsOn:
      - ApiGw1Rest
      - ApiGw1IntegrationWithLambdaApi1
    Properties:
      # Description: "Route to LambdaApi1 for API Gateway1" # property not allowed for AWS::ApiGatewayV2::Route
      ApiId: !Ref ApiGw1Rest
      RouteKey: GET /user/{userId}/calendar
      Target: !Join
        - /
        - - integrations
          - !Ref ApiGw1IntegrationWithLambdaApi1

  ApiGw1RouteGetUserProjects:
    Type: AWS::ApiGatewayV2::Route
    DependsOn:
      - ApiGw1Rest
      - ApiGw1IntegrationWithLambdaApi1
    Properties:
      # Description: "Route to LambdaApi1 for API Gateway1" # property not allowed for AWS::ApiGatewayV2::Route
      ApiId: !Ref ApiGw1Rest
      RouteKey: GET /user/{userId}/projects
      Target: !Join
        - /
        - - integrations
          - !Ref ApiGw1IntegrationWithLambdaApi1

#Outputs:
#  LambdaFunctionOutput:
#    Value: !Ref LambdaApi1
#    Description: Return Value of Lambda Function