name: aws-lambdas.build-release-docker

on:
  workflow_dispatch:

jobs:
  build-release-docker-job:
    runs-on: ubuntu-latest # ubuntu-22.04
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      - name: Build docker image
        run: DOCKER_BUILDKIT=1 docker build -t gr/plaax-nodejs/build-release -f ./operations/aws-lambdas/build-release/all-steps.dockerfile .
      - name: Run docker image
        run: docker run
          --platform linux/x86_64
          --env ENV_NAME=dev
          --env RELEASE_HASH=$(git rev-parse HEAD)
          --env AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          --env AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          --env AWS_DEFAULT_REGION=eu-west-1
          --env AWS_REGION=eu-west-1
          --env AWS_DEFAULT_OUTPUT=json
          gr/plaax-nodejs/build-release
