name: release-and-deploy

# >>>> What to do:
# (premise: it seems we cannot manually trigger a specific job, so manual-run => split into a single wf)
# - 1 workflow = build, test, release
#   - (job has to be 'reusable' / step is strictly part of the job)
#   - job: ubuntu-latest, no env needed
#   - step: checkout
#   - step: install (./build-release.sh --install)
#   - step: test (./build-release.sh --test)
#   - step: build the release (./build-release.sh --build)
#   - step: upload the release on s3 (./build-release.sh --release)
# - N workflows = deploy (by env)
#   - job: ubuntu-latest, env mandatory
#   - step: (./deploy.sh --get-latest-release)
#   - step: (./deploy.sh --deploy-stack)

# Something to check before to proceed:
# - research how to force CFN to deploy if file has the same name
#   - if we cannot force lambda deploy, get file from S3 by prefix (newest)

on:
  workflow_dispatch:

jobs:
  release-job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check aws cli version
        run: aws --version
      - name: Build docker image from base-shared-img
        run: echo "Building docker image..."
      - name: Test the code
        run: echo "Testing..."
      - name: Build the release
        run: echo "Building..."
      - name: Upload the release
        run: echo "Uploading release to AWS S3..."
  deploy-job-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Build docker image2 from base-shared-img
        run: echo "Building docker image2 dev..."
      - name: Deploy
        run: echo "Deploying env..."
  deploy-job-prd:
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: Build docker image2 from base-shared-img
        run: echo "Building docker image2 prd..."
      - name: Deploy
        run: echo "Deploying prd..."
